use crate::error::CodeGenError;
use crate::ir_engine::{IrModule, IrOp, IrConst, Terminator, BasicBlock, BlockId, IrValue};
use super::rename::VariableRenamer;
use std::collections::{HashSet, HashMap};

#[allow(missing_docs)]
pub struct Emitter {
    buffer: String,
    indent_level: usize,
    inline_exprs: HashMap<IrValue, String>,
    use_counts: HashMap<IrValue, usize>,
}

impl Default for Emitter {
    fn default() -> Self {
        Self::new()
    }
}

impl Emitter {
    #[allow(missing_docs)]
    pub fn new() -> Self {
        Self {
            buffer: String::new(),
            indent_level: 0,
            inline_exprs: HashMap::new(),
            use_counts: HashMap::new(),
        }
    }

    #[allow(missing_docs)]
    pub fn emit_module(&mut self, module: &IrModule, ren: &VariableRenamer) -> Result<(), CodeGenError> {
        self.write_line("-- Generated by lunadec");
        self.write_line(&format!("-- Entry point: {}", module.entry));
        self.write_line("");

        for func in &module.functions {
            if func.id.0 == module.entry.0 {
                // Def-Use counts for dynamic expression reconstruction
                self.use_counts.clear();
                for block in func.blocks.values() {
                    for op in &block.ops {
                        let uses = self.get_uses(op);
                        for u in uses {
                            *self.use_counts.entry(u).or_insert(0) += 1;
                        }
                    }
                    match &block.terminator {
                        Terminator::CondBranch(c, _, _) => { *self.use_counts.entry(*c).or_insert(0) += 1; }
                        Terminator::Return(rets) => { for r in rets { *self.use_counts.entry(*r).or_insert(0) += 1; } }
                        Terminator::TailCall(c, args) => { *self.use_counts.entry(*c).or_insert(0) += 1; for r in args { *self.use_counts.entry(*r).or_insert(0) += 1; } }
                        _ => {}
                    }
                }

                let mut emitted_blocks = HashSet::new();
                let mut current_block = Some(BlockId(0));

                while let Some(bid) = current_block {
                    if emitted_blocks.contains(&bid) {
                        self.write_line(&format!("goto L{}", bid.0));
                        break;
                    }
                    emitted_blocks.insert(bid);

                    if let Some(block) = func.blocks.get(&bid) {
                        // Omit labels if not target of complex jumps?
                        // For now we just emit
                        // self.write_line(&format!("::L{}::", bid.0));
                        self.emit_block(block, ren)?;

                        match &block.terminator {
                            Terminator::Branch(next) => {
                                current_block = Some(*next);
                            }
                            Terminator::CondBranch(cond, tb, fb) => {
                                let c_name = self.resolve_val(*cond, ren)?;
                                self.write_line(&format!("if {} then goto L{} else goto L{} end", c_name, tb.0, fb.0));
                                current_block = None;
                            }
                            Terminator::Return(rets) => {
                                if !rets.is_empty() {
                                    let r_names: Result<Vec<_>, _> = rets.iter().map(|&r| self.resolve_val(r, ren)).collect();
                                    self.write_line(&format!("return {}", r_names?.join(", ")));
                                } else {
                                    // if it's main module implicit return don't emit if empty
                                    // self.write_line("return");
                                }
                                current_block = None;
                            }
                            Terminator::TailCall(c, args) => {
                                let c_name = self.resolve_val(*c, ren)?;
                                let a_names: Result<Vec<_>, _> = args.iter().map(|&r| self.resolve_val(r, ren)).collect();
                                self.write_line(&format!("return {}({})", c_name, a_names?.join(", ")));
                                current_block = None;
                            }
                            Terminator::Unreachable => {
                                current_block = None;
                            }
                        }
                    } else {
                        break;
                    }
                }
            }
        }
        Ok(())
    }

    fn get_uses(&self, op: &IrOp) -> Vec<IrValue> {
        let mut uses = Vec::new();
        match op {
            IrOp::Move(_, s) => { uses.push(*s); }
            IrOp::Add(_, a, b) | IrOp::Sub(_, a, b) | IrOp::Mul(_, a, b) | IrOp::Div(_, a, b) | IrOp::Mod(_, a, b) | IrOp::Pow(_, a, b) => {
                uses.push(*a); uses.push(*b);
            }
            IrOp::Unm(_, a) | IrOp::Not(_, a) | IrOp::Len(_, a) => {
                uses.push(*a);
            }
            IrOp::Call(_, f, args) => {
                uses.push(*f);
                uses.extend(args);
            }
            IrOp::SetGlobal(_, a) | IrOp::SetUpvalue(_, a) => {
                uses.push(*a);
            }
            IrOp::SetTable(a, b, c) => {
                uses.push(*a); uses.push(*b); uses.push(*c);
            }
            IrOp::GetTable(_, t, k) => {
                uses.push(*t); uses.push(*k);
            }
            IrOp::Eq(_, b, c) | IrOp::Lt(_, b, c) | IrOp::Le(_, b, c) => {
                uses.push(*b); uses.push(*c);
            }
            IrOp::Concat(_, args) => {
                uses.extend(args);
            }
            IrOp::Test(_, s) => { uses.push(*s); }
            IrOp::TestSet(_, a, b) => { uses.push(*a); uses.push(*b); }
            IrOp::SelfOp(_, a, b) | IrOp::TForLoop(_, a, b) => { uses.push(*a); uses.push(*b); }
            IrOp::ForLoop(_, s) | IrOp::ForPrep(_, s) => { uses.push(*s); }
            _ => {}
        }
        uses
    }

    fn resolve_val(&mut self, val: IrValue, ren: &VariableRenamer) -> Result<String, CodeGenError> {
        if let Some(inline) = self.inline_exprs.remove(&val) {
            Ok(inline)
        } else {
            Ok(ren._get(val)?.to_string())
        }
    }

    fn maybe_inline(&mut self, dest: IrValue, expr: String, ren: &VariableRenamer) -> Result<(), CodeGenError> {
        let count = *self.use_counts.get(&dest).unwrap_or(&0);
        if count == 1 {
            self.inline_exprs.insert(dest, expr);
        } else {
            self.write_line(&format!("local {} = {}", ren._get(dest)?, expr));
        }
        Ok(())
    }

    fn emit_block(&mut self, block: &BasicBlock, ren: &VariableRenamer) -> Result<(), CodeGenError> {
        for op in &block.ops {
            match op {
                IrOp::LoadConst(dest, c) => {
                    let v = match c {
                        IrConst::Nil => "nil".to_string(),
                        IrConst::Bool(b) => b.to_string(),
                        IrConst::Number(n) => n.to_string(),
                        IrConst::String(s) => format!("{:?}", String::from_utf8_lossy(s)),
                    };
                    self.maybe_inline(*dest, v, ren)?;
                }
                IrOp::Move(dest, src) => {
                    let s_str = self.resolve_val(*src, ren)?;
                    self.maybe_inline(*dest, s_str, ren)?;
                }
                IrOp::GetGlobal(dest, name) => {
                    self.maybe_inline(*dest, name.clone(), ren)?;
                }
                IrOp::SetGlobal(name, src) => {
                    let s_str = self.resolve_val(*src, ren)?;
                    self.write_line(&format!("{} = {}", name, s_str));
                }
                IrOp::GetTable(dest, t, k) => {
                    let t_str = self.resolve_val(*t, ren)?;
                    let k_str = self.resolve_val(*k, ren)?;
                    self.maybe_inline(*dest, format!("{}[{}]", t_str, k_str), ren)?;
                }
                IrOp::SetTable(t, k, v) => {
                    let t_str = self.resolve_val(*t, ren)?;
                    let k_str = self.resolve_val(*k, ren)?;
                    let v_str = self.resolve_val(*v, ren)?;
                    self.write_line(&format!("{}[{}] = {}", t_str, k_str, v_str));
                }
                IrOp::NewTable(dest) => {
                    self.maybe_inline(*dest, "{}".to_string(), ren)?;
                }
                IrOp::Add(dest, a, b) => {
                    let a_str = self.resolve_val(*a, ren)?;
                    let b_str = self.resolve_val(*b, ren)?;
                    self.maybe_inline(*dest, format!("{} + {}", a_str, b_str), ren)?;
                }
                IrOp::Sub(dest, a, b) => {
                    let a_str = self.resolve_val(*a, ren)?;
                    let b_str = self.resolve_val(*b, ren)?;
                    self.maybe_inline(*dest, format!("{} - {}", a_str, b_str), ren)?;
                }
                IrOp::Mul(dest, a, b) => {
                    let a_str = self.resolve_val(*a, ren)?;
                    let b_str = self.resolve_val(*b, ren)?;
                    self.maybe_inline(*dest, format!("{} * {}", a_str, b_str), ren)?;
                }
                IrOp::Div(dest, a, b) => {
                    let a_str = self.resolve_val(*a, ren)?;
                    let b_str = self.resolve_val(*b, ren)?;
                    self.maybe_inline(*dest, format!("{} / {}", a_str, b_str), ren)?;
                }
                IrOp::Mod(dest, a, b) => {
                    let a_str = self.resolve_val(*a, ren)?;
                    let b_str = self.resolve_val(*b, ren)?;
                    self.maybe_inline(*dest, format!("{} % {}", a_str, b_str), ren)?;
                }
                IrOp::Pow(dest, a, b) => {
                    let a_str = self.resolve_val(*a, ren)?;
                    let b_str = self.resolve_val(*b, ren)?;
                    self.maybe_inline(*dest, format!("{} ^ {}", a_str, b_str), ren)?;
                }
                IrOp::Concat(dest, args) => {
                    let mut a_strs = Vec::new();
                    for &arg in args {
                        a_strs.push(self.resolve_val(arg, ren)?);
                    }
                    self.maybe_inline(*dest, a_strs.join(" .. "), ren)?;
                }
                IrOp::Call(rets, f, args) => {
                    let f_str = self.resolve_val(*f, ren)?;
                    let mut a_strs = Vec::new();
                    for &arg in args {
                        a_strs.push(self.resolve_val(arg, ren)?);
                    }

                    if rets.is_empty() {
                        self.write_line(&format!("{}({})", f_str, a_strs.join(", ")));
                    } else if rets.len() == 1 {
                        self.maybe_inline(rets[0], format!("{}({})", f_str, a_strs.join(", ")), ren)?;
                    } else {
                        let mut r_names = Vec::new();
                        for &r in rets {
                            r_names.push(ren._get(r)?.to_string());
                        }
                        self.write_line(&format!("local {} = {}({})", r_names.join(", "), f_str, a_strs.join(", ")));
                    }
                }
                _ => {}
            }
        }
        Ok(())
    }

    #[allow(missing_docs)]
    pub fn into_string(self) -> String {
        self.buffer
    }

    fn _indent(&mut self) {
        for _ in 0..self.indent_level {
            self.buffer.push_str("    ");
        }
    }

    fn write_line(&mut self, line: &str) {
        self._indent();
        self.buffer.push_str(line);
        self.buffer.push('\n');
    }
}
