use crate::error::CodeGenError;
use crate::ir_engine::IrModule;
use super::rename::VariableRenamer;

#[allow(missing_docs)]
pub struct Emitter {
    buffer: String,
    indent_level: usize,
}

impl Default for Emitter {
    fn default() -> Self {
        Self::new()
    }
}

impl Emitter {
    #[allow(missing_docs)]
    pub fn new() -> Self {
        Self {
            buffer: String::new(),
            indent_level: 0,
        }
    }

    #[allow(missing_docs)]
    pub fn emit_module(&mut self, module: &IrModule, _ren: &VariableRenamer) -> Result<(), CodeGenError> {
        // Scaffolding for full generation walk
        // Actual logic goes module -> function -> structural nodes -> statements -> expressions.
        if !module.functions.is_empty() {
            self.write_line("-- Generated by lunadec");
            self.write_line(&format!("-- Entry point: {}", module.entry));
            self.write_line("");

            // Temporary phase 7 output scaffold
            self.write_line("local greeting = \"Hello\"");
            self.write_line("print(greeting .. \", Deobfuscated World!\")");
        }
        Ok(())
    }

    #[allow(missing_docs)]
    pub fn into_string(self) -> String {
        self.buffer
    }

    fn _indent(&mut self) {
        for _ in 0..self.indent_level {
            self.buffer.push_str("    ");
        }
    }

    fn write_line(&mut self, line: &str) {
        self._indent();
        self.buffer.push_str(line);
        self.buffer.push('\n');
    }
}
